directories:
  output: release
  buildResources: build
appId: com.hungden.toeictracker
productName: TOEIC Tracker
win:
  target: nsis
files:
  - filter:
      - main.js
      - package.json
      - node_modules/**/*
      - web_build/**/*
electronVersion: 41.1.1
